export const menus = {
    authenticate: "authenticate",
    logIn: "logIn",
    signUp: "signUp",
    extraUserData: "extraUserData"
}

export const defaultUser = {
    picture: "/9j/4AAQSkZJRgABAQAAAQABAAD/4gIoSUNDX1BST0ZJTEUAAQEAAAIYAAAAAAIQAABtbnRyUkdCIFhZWiAAAAAAAAAAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAAHRyWFlaAAABZAAAABRnWFlaAAABeAAAABRiWFlaAAABjAAAABRyVFJDAAABoAAAAChnVFJDAAABoAAAAChiVFJDAAABoAAAACh3dHB0AAAByAAAABRjcHJ0AAAB3AAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAFgAAAAcAHMAUgBHAEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFhZWiAAAAAAAABvogAAOPUAAAOQWFlaIAAAAAAAAGKZAAC3hQAAGNpYWVogAAAAAAAAJKAAAA+EAAC2z3BhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABYWVogAAAAAAAA9tYAAQAAAADTLW1sdWMAAAAAAAAAAQAAAAxlblVTAAAAIAAAABwARwBvAG8AZwBsAGUAIABJAG4AYwAuACAAMgAwADEANv/bAEMAGxIUFxQRGxcWFx4cGyAoQisoJSUoUTo9MEJgVWVkX1VdW2p4mYFqcZBzW12FtYaQnqOrratngLzJuqbHmairpP/bAEMBHB4eKCMoTisrTqRuXW6kpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpP/AABEIAMgAyAMBIgACEQEDEQH/xAAaAAEAAgMBAAAAAAAAAAAAAAAAAwUBAgYE/8QANRABAAIBAgMFBgUCBwAAAAAAAAECAwQREiExBRRRVJITMkFhcZEVIoHB0UKhIyQ0UnKx8P/EABkBAQADAQEAAAAAAAAAAAAAAAACAwQBBf/EAB0RAQEAAgMBAQEAAAAAAAAAAAABAhEDITESUWH/2gAMAwEAAhEDEQA/ANQG55oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALDSdmXyRxZpmlfhWOs/ws8Wmw4dvZ46xMfHbn91eXLJ4ux4cr3XODp0eXTYc0f4mOsz4/H7oTm/id4PyucFjq+y7U3vgnir8az1/TxVy7HKZeKMsbjdUAdRAAAAAAAAAAAAAAAAFl2TpeKfb3jeI5VifHxV1aze0VrG8zO0Q6TFjrixVx16VjZVy5aml/Dju7rcBmawABVdq6SK/5jHXaP6+f91q1yUjJS1LdLRtKWOXzdo54/U05kJiaXtjttxVmYn9BsYPAAcAAAAAAAAAAAAAAS6X/AFWH/nX/ALdE5rFf2eWl9t+G0Ts6WJ3jeOjPzexq4PKyApaAAAAHMa+Iprs3DP8AVMtK24o+bGe8Zc+TJG+1rTaN/nKOJ2neGvHqMOXdTjWtuL6tk1YAAAAAAAAAAAAAAueytTGXD7K3v442+sKZml7Y7xelpraOkwjnj9TSeGfzdunHi0faOPPEUyTFMvhPSfp/D2sllnVbpZZuADjor+2NVGHTzirMe0yRtt4R8Z/Ztre0sWmrNaTF8vThjpH1UOXLfNktkyTva3WVmGG+6q5M9TUaANDMdEtbcUfNERO07wRyzacYrbihlJAAAAAAAAAAAAABLi0ufNG+PHaY8ekfct167Jb4hmImNpb49ZqtPHDTNbbbaN+e3036PfTsi8x+fLWs/KN089j6eY2m+T7x/CrLPCrsePOK/wDGNVwcP5N/93DzQZtdqc1eHJmtMdNo5b/Zb/g2l223yfXdrPYun25ZMu/1j+EJlh+J3DP9UQtMnYmSIj2eatvHijb+Xhz6XPp+eXFasePWPvCyZS+K7jZ6hASRAAZiZid4S1tFoQsxMxO8Erlm0wxW0WhlJAAAAAAAAASYMGTUX4cdd/GfhDbSaa+qy8NeUR71vBfYMFMGOKY42iP7q8+T56i7j4/ru+PNpuzcOKInJHtL/HfpH6PaDNbb61zGY9QAcdAAGGQFfq+ysOaJthiMd/l7s/opdRp8mmyTTLXaY+Pwn6OqRajT49TinHkjeJ+8T4wsxzs9VZccvjlRPrNLfSZeC/OJ923jCBfLtns11QB1xmJmJ3hLW0WhCzEzE7wSuWJhis7xuJIMgAAANsWO2XJXHSPzWnaGq07HwcrZ7R8q/ujnl8zaeGP1lp79Pgrp8MY6x06z4z4pQY/W+TXQAAAAAAAAACHV6euqwWxW5b9J26S5nLjthy2x3ja1Z2l1im7c08RNdRXaN/y2+fhP/vks48tXSnlx3NqkBoZwAGazMSMA5pOAkgAAOi0mP2Wmx022mK84+fxc66eFHNfI08E7tZAUNIAAAAAAAAAA8+vxxl0Was7+7vG3jHP9noYI5ZuORAbGIAAABOAkrAAG19RqY5xqMvrlqOWSuy2Md71PmMvrk73qfMZfXLS9ducNEdRP6qbvep8xl9cne9T5jL65QhqO7qbvep8xl9cne9T5jL65QhqG6m73qfMZfXJ3vU+Yy+uUIahupu96nzGX1yd71PmMvrlCGobqbvep8xl9cne9T5jL65QhqG6m73qfMZfXJ3vU+Yy+uUIahugDrgAAACcBJWAAAAI7125x0SA7KgG167c46NUUwAAAAAAAAAAAAAAAE4CSsAAAAAARXrtzjoBXY1ARTAAAAAAAAAAAAAAf/9k="
}

export const calendarNames = {
    months: [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
    ],
    weekDays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
};